config/routes.rb
Csvdeal::Application.routes.draw do
  resources :documentos

end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :code
  attr_accessible :tomado
  after_initialize :init
  # Códigos numéricos para los códigos de barra de cada envío
  # rrrrrr12345678 (r = reservado, primera serie 000000)
  # primera serie I00000.00000001,I00000.009999 (el punto no va, es solo para no perderme)


  BASE="I00000"
  DIGITOS_VALIDOS=8
  DIGITO_DE_RELLENO="0"

  def init
    self.tomado ||= false
  end

 def self.agregar(cantidad=1)
    defaults = {}
    numero = last ? ( last.code.slice(6..13).to_i + 1 ) : 1
    ( (numero)..(numero+cantidad-1) ).each do |n|
      Code.create :code => generar( n )
    end
 end

 def self.generar(numero)
    resultado = rellenar(numero)
    BASE+resultado
 end

 def self.rellenar(num)
   s = DIGITO_DE_RELLENO*DIGITOS_VALIDOS
   s.insert(-(num.to_s.length + 1), num.to_s)[0, s.length - num.to_s.length] if num.to_s.length <= s.length
 end

end

app/models/documento.rb
class Documento < ActiveRecord::Base 
  attr_accessible :csv_file
  attr_accessible :ordenando
  attr_accessible :ordenando_uuid
  attr_accessible :remitente, :direccion_del_remitente, :tipo_de_envio
  # TODO: estoy seguro que la línea abajo se puede escribir mejor
  has_attached_file :csv_file ,:styles => { :cantv => { :quality => :better } }, :processors => ['cantv']
  validates_presence_of :tipo_de_envio
  validates_presence_of :remitente
  validates_presence_of :direccion_del_remitente

  after_initialize :init

  def init
    self.tipo_de_envio ||= "Documento"     #will set the default value only if it's nil
    self.remitente ||= "Ipostel"     #will set the default value only if it's nil
    self.direccion_del_remitente ||= "San Martín, Caracas, DC."     #will set the default value only if it's nil
  end

  ####### Componer significa por ahora generar los CSV de acuerdo a un worker dado
  def componer_superlinea2en1
    params = {}
    params["campo"]="nombre"
    params["ascendente"]="ascendente"
    params["id"]=self.id.to_s
    # TODO: renombre worker a dos_en_uno_antiguo o algo así no se usa
    # Recordemos la superlínea
    Resque.enqueue(ComponiendoWorker, params)   
  end
  
  def componer_telco
    # TODO: renombre worker a telco o algo así
    # Fue el que se usó en impresión Telco
    params = {}
    params["campo"]="nombre"
    params["ascendente"]="ascendente"
    params["id"]=self.id.to_s
    Resque.enqueue(TelcoWorker, params)   
  end

  def componer_caveguias
    # Fue el que se usó en impresión Caveguías
    params = {}
    params["campo"]="nombre"
    params["ascendente"]="ascendente"
    params["id"]=self.id.to_s
    Resque.enqueue(CaveguiasWorker, params)   
  end

  def componer_fama
    # Sera el que se use con Fama
    params = {}
    params["campo"]="nombre"
    params["ascendente"]="ascendente"
    params["id"]=self.id.to_s
    Resque.enqueue(FamaWorker, params)   
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documentos_controller.rb
class DocumentosController < ApplicationController
  # GET /documentos
  # GET /documentos.json
 def import
   require 'csv'
   csv_text = File.read(params[:file].tempfile.to_path.to_s)
 end 

 def index
    @documentos = Documento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documentos }
    end
  end

  # GET /documentos/1
  # GET /documentos/1.json
  def show
    @documento = Documento.find(params[:id])

    # Verificar params para ordenado
    if params[:commit].eql?("Ordenar")
      if @documento.ordenando
        flash[:notice]="Espere hasta que termine de ordenar"
        flash[:estado]="0"
      else
        Resque.enqueue(OrderingWorker, params)   
        flash[:notice]="Su documento ya está en cola ordenándose"
        flash[:estado]="0"
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @documento }
    end
  end

  # GET /documentos/new
  # GET /documentos/new.json
  def new
@documento = Documento.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @documento }
    end
  end

  # GET /documentos/1/edit
  def edit
    @documento = Documento.find(params[:id])
  end

  # POST /documentos
  # POST /documentos.json
  def create
    @documento = Documento.new(params[:documento])

    respond_to do |format|
      if @documento.save
        format.html { 
		redirect_to @documento , notice: 'Documento creado con éxito.', flash: {estado: 0}
        }
        format.json { render json: @documento, status: :created, location: @documento }
      else
        format.html { render action: "new" }
        format.json { render json: @documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documentos/1
  # PUT /documentos/1.json
  def update
    @documento = Documento.find(params[:id])

    respond_to do |format|
      if @documento.update_attributes(params[:documento])
        format.html { redirect_to @documento, notice: 'Documento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentos/1
  # DELETE /documentos/1.json
  def destroy
    @documento = Documento.find(params[:id])
    @documento.destroy

    respond_to do |format|
      format.html { redirect_to documentos_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/views/documentos/_form.html.erb
<%= form_for(@documento , :html => { :multipart => true }) do |f| %>
  <% if @documento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@documento.errors.count, "error") %> provocaron que no se pudiera guardar el documento:</h2>

      <ul>
      <% @documento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="remitente">
    <%= label_tag("Remitente") %>
    <%= f.text_field :remitente %>
  </div>

  <div id="direccion_del_remitente">
    <%= label_tag("Dirección del remitente") %>
    <%= f.text_field :direccion_del_remitente %>
  </div>

  <div id="tipo_de_envio">
    <%= label_tag("Tipo de envío") %>
    <%= f.text_field :tipo_de_envio, :readonly => true %>
  </div>

  <div id="csv_file">
    <%= f.file_field :csv_file %>
  </div>
  
  <div id="csv_file_filtro">
  <%=  select_tag "filtro", 
         options_for_select([['CANTV', 'cantv'], 
                            ['PDVSA', 'pdvsa'],
                            ['FANB', 'fanb'],
                            ['FANB Armada', 'armada']]) %> 
  </div>


  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/documentos/_order.html.erb
<%= form_for(@documento , method: "get") do |f| %>

  <div id="csv_file_order">
    <h2><%= label_tag("Ordenamiento del documento") %></h2>
    <%= label_tag "Seleccione campo:" %>
    <%=  select_tag "campo", 
         options_for_select([['nombre', 'nombre'], 
                            ['apellido', 'apellido'],
                            ['direccion', 'direccion'],
                            ['estado', 'estado'],
                            ['ciudad', 'ciudad']]) %> 
  </div>
  
  <div id="csv_file_order_criterio">
    <%= label_tag "Seleccione ascendente o descente:" %>
    <%= select_tag "ascendente",
    options_for_select([['ascendente','ascendente'],
                        ['descendiente', 'descendiente']]) %>
  </div>

  <div class="actions">
    <%= f.submit "Ordenar" %>
  </div>
<% end %>

app/views/documentos/edit.html.erb
<h1>Editing documento</h1>

<%= render 'form' %>

<%= link_to 'Show', @documento %> |
<%= link_to 'Back', documentos_path %>

app/views/documentos/index.html.erb
<h1>Listado de documentos CSV cargados</h1>

<table>
  <tr>
    <th>Remitente</th>
    <th>Tipo de envío</th>
    <th>Nombre</th>
    <th></th>
  </tr>

<% @documentos.each do |documento| %>
  <tr>
    <td><%= documento.remitente %></td>
    <td><%= documento.tipo_de_envio %></td>
    <td><%= documento.csv_file_file_name %></td>

    <td><%= link_to 'Mostrar', documento %></td>
    <td><%= link_to 'Editar', edit_documento_path(documento) %></td>
    <td><%= link_to 'Eliminar', documento, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Documento', new_documento_path %>

app/views/documentos/new.html.erb
<h1>Carga de nuevo documento CSV</h1>

<%= render 'form' %>

<%= link_to 'Atrás', documentos_path %>

app/views/documentos/show.html.erb
<p id="notice"><%= notice %></p>
<p id="status" style="{display:none}"><%= flash[:estado] %></p>

<h2>Datos generales</h2>

  <div id="remitente">
    <%= label_tag("Remitente:") %>
    <%= @documento.remitente %>
  </div>

  <div id="direccion_del_remitente">
    <%= label_tag("Dirección del remitente:") %>
    <%= @documento.direccion_del_remitente %>
  </div>

  <div id="tipo_de_envio">
    <%= label_tag("Tipo de envío:") %>
    <%= @documento.tipo_de_envio %>
  </div>

  <div id="nombre_de_archivo">
    <%= label_tag("Nombre de archivo:") %>
    <%= @documento.csv_file_file_name %>
  </div>

<%= render "order" %>

<h2>Enlaces de descarga</h2>
<ul>
  <li><%= link_to "Original", @documento.csv_file.url %>
  </li>
  <li><%= link_to "Preprocesado para CANTV", @documento.csv_file.url(:cantv) %>
  </li>
  <%#= link_to "Ordenado", @documento.csv_file.url(:cantv) if @documento.ordenando_uuid?%>
  <li>
  <%= link_to "Ordenado", @documento.csv_file.url(:cantv) if @documento.ordenando.eql?(false) %></li>
</ul>
<%= link_to 'Indice de documentos', documentos_path %>

<h3>Depuración (ignore)</h3>
<% if @documento.ordenando? %>
  <p>Su documento se está ordenando</p>
<% end %>

<p>uuid:<%= @documento.ordenando_uuid.to_s %></p>
<p>ordenando?:<%= @documento.ordenando.to_s %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Csvdeal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>